openapi: 3.0.3
info:
  title: Codegen Service API
  version: 0.1.0
servers:
  - url: http://localhost:7007
paths:
  /compile:
    post:
      summary: Generate an artifact from IR and SymTab
      operationId: compile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                icodeId: { type: string }
                symTabId: { type: string }
                options:
                  type: object
                  additionalProperties: true
              required: [icodeId, symTabId]
      responses:
        "200":
          description: Compile result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompileResult"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /artifacts/{id}:
    get:
      summary: Get artifact metadata
      operationId: getArtifact
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Artifact
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Artifact"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /artifacts/{id}/download:
    get:
      summary: Download artifact binary
      operationId: downloadArtifact
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Binary artifact
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    CompileResult:
      type: object
      additionalProperties: false
      properties:
        artifactId: { type: string }
        instructionCount: { type: integer }
        elapsedMs: { type: integer }
      required: [artifactId, instructionCount, elapsedMs]
    Artifact:
      type: object
      additionalProperties: false
      properties:
        id: { type: string }
        sizeBytes: { type: integer }
        createdAt: { type: string, format: date-time }
        mediaType: { type: string }
    Error:
      type: object
      additionalProperties: false
      properties:
        code:
          type: string
          description: Application-specific error code
        message:
          type: string
        details:
          description: Optional structured error details
          anyOf:
            - type: object
            - type: array
            - type: string
      required: [code, message]
